name: "Failed Build Issue"
description: "Create or comment on an issue when your GitHub Actions workflow fails."
inputs:
  github-token:
    description: "GitHub token with repository access, i.e., secrets.GITHUB_TOKEN"
    required: true
  label-name:
    description: "name of label that this action interacts with"
    required: true
    default: "build failed"
  title-template:
    description: "mustache template to use as title when creating a new issue"
    required: true
    default: "Failed build on main branch ({{workflow}} #{{runNumber}})"
  body-template:
    description: "mustache template to use for issue or comment body"
    required: true
    default: |
      Workflow failed: [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runNumber}})
outputs:
  issue-number: # output will be available to future steps
    description: "Issue number of new issue or comment"
runs:
  using: "node16"
  main: "dist/index.js"
