name: "Failed Build Issue"
description: "Create or comment on an issue when your GitHub Actions workflow fails."
inputs:
  github-token:
    description: "GitHub token with repository access, i.e., secrets.GITHUB_TOKEN"
    required: true
  label-name:
    description: "Name of label that this action interacts with"
    required: true
    default: "build failed"
  title-template:
    description: "Mustache template to use as title when creating a new issue"
    required: true
    default: "Failed build: {{workflow}}"
  body-template:
    description: "Mustache template to use for issue or comment body"
    required: true
    default: |
      GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runNumber}}) failed.

      Event: {{eventName}}
      Branch: [{{refname}}](https://github.com/{{repo.owner}}/{{repo.repo}}/tree/{{refname}})
      Commit: [{{sha}}](https://github.com/{{repo.owner}}/{{repo.repo}}/commit/{{sha}})
  create-label:
    description: "Whether to create a new label for 'label-name' if it doesn't already exist."
    required: true
    default: true
  always-create-new-issue:
    description: "If true, will always create a new issue, even if one matching 'label-name' is already open."
    required: true
    default: false
outputs:
  issue-number: # output will be available to future steps
    description: "Issue number of new issue or comment"
runs:
  using: "node16"
  main: "dist/index.js"
